### ISSUE TITLE
Not able to find the train.py file 

### ISSUE THREAD

**Issue by venkateshbabusekar** [EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#151]
can you please advice where to find the train.py . I have completed all the steps prior to that train.py step. 
Any help you really appreciate

**Comment by Sibozhu** [comment]
> can you please advice where to find the train.py . I have completed all the steps prior to that train.py step.
> Any help you really appreciate
In section 2a, he wrote:
(Note, this tutorial was done using this [GitHub commit](https://github.com/tensorflow/models/tree/079d67d9a0b3407e8d074a200780f3835413ef99) of the TensorFlow Object Detection API. If portions of this tutorial do not work, it may be necessary to download and use this exact commit rather than the most up-to-date version.)

I believe what you need to do is just go to that certain commit of Tensorflow API and you'll be good.

**Comment by bolokoz** [comment]
it's inside legacy folder

**Comment by EdjeElectronics** [comment]
Thanks for helping out @Sibozhu and @bolokoz ! I updated the guide to mention that the train.py file is now in the legacy folder.
